### ISSUE TITLE
I don't think bears have a concept of gender.

### ISSUE THREAD

**Issue by JesseNReynolds** [learn-co-curriculum/sql-organizing-bears-lab#4]
I understand this is a simple mistake or a carryover from several years ago when the issue was less out-in-front, but the database column really should be "sex" and not "gender". It's not only more sensitive to people who are non-binary but more likely the descriptor we're looking for. : )

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas, the update may not appear right away.

If you do not believe that the issue has been addressed, please re-open this issue. 💙
